<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Animal Report</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12px;
            color: #333;
        }
        h1, h2, h3 {
            color: #2c3e50;
        }
        .header {
            text-align: center;
            padding: 10px 0;
            border-bottom: 2px solid #3498db;
        }
        .summary {
            background-color: #ecf0f1;
            padding: 15px;
            margin: 20px 0;
            border-left: 4px solid #2980b9;
        }
        .section-title {
            background-color: #3498db;
            color: white;
            padding: 8px;
            margin-top: 30px;
            font-weight: bold;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th {
            background-color: #2980b9;
            color: white;
            padding: 8px;
            text-align: left;
        }
        td {
            padding: 6px;
            border-bottom: 1px solid #ddd;
        }
        .footer {
            position: fixed;
            bottom: 30px;
            left: 0;
            right: 0;
            text-align: center;
            color: #aaa;
            font-size: 11px;
        }
    </style>
</head>
<body>

    <div class="header">
        <h1>Animal Report</h1>
        <p>Generated by: {{ auth()->user()->complete_name }}</p>
        <p>Date Range: {{ $dateFrom->format('F d, Y') }} - {{ $dateTo->format('F d, Y') }}</p>
    </div>

    <div class="summary">
        <h3>Summary</h3>
        <p><strong>Total Animals:</strong> {{ $summary['total'] }}</p>
        <p><strong>Vaccinated:</strong> {{ $summary['vaccinated'] }}</p>
        <p><strong>Not Vaccinated:</strong> {{ $summary['nonVaccinated'] }}</p>
    </div>

    <div>
        <div class="section-title">Animals by Species</div>
        <table>
            <thead>
                <tr>
                    <th>Species</th>
                    <th>Total</th>
                    <th>Vaccinated</th>
                    <th>Not Vaccinated</th>
                </tr>
            </thead>
            <tbody>
                @foreach($summary['bySpecies'] as $species => $data)
                    <tr>
                        <td>{{ $species }}</td>
                        <td>{{ $data['count'] }}</td>
                        <td>{{ $data['vaccinated'] }}</td>
                        <td>{{ $data['nonVaccinated'] }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div>
        <div class="section-title">Animals by Breed</div>
        <table>
            <thead>
                <tr>
                    <th>Breed</th>
                    <th>Total</th>
                    <th>Vaccinated</th>
                    <th>Not Vaccinated</th>
                </tr>
            </thead>
            <tbody>
                @foreach($summary['byBreed'] as $breed => $data)
                    <tr>
                        <td>{{ $breed }}</td>
                        <td>{{ $data['count'] }}</td>
                        <td>{{ $data['vaccinated'] }}</td>
                        <td>{{ $data['nonVaccinated'] }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div>
        <div class="section-title">Animal List</div>
        <table>
            <thead>
                <tr>
                    <th>Animal Name</th>
                    <th>Species</th>
                    <th>Breed</th>
                    <th>Owner</th>
                    <th>Vaccinated</th>
                    <th>Date Registered</th>
                </tr>
            </thead>
            <tbody>
                @foreach($animals as $animal)
                    <tr>
                        <td>{{ $animal->name }}</td>
                        <td>{{ $animal->species->name ?? 'N/A' }}</td>
                        <td>{{ $animal->breed->name ?? 'N/A' }}</td>
                        <td>{{ $animal->owner->user->complete_name ?? 'N/A' }}</td>
                        <td>{{ $animal->is_vaccinated ? 'Yes' : 'No' }}</td>
                        <td>{{ \Carbon\Carbon::parse($animal->created_at)->format('F d, Y') }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="footer">
        Animal Report | Generated on {{ now()->format('F d, Y H:i A') }}
    </div>

</body>
</html>
