<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Animal Report</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12px;
            color: #000000;
            margin: 0;
            padding: 20px;
        }
        
        .header {
            background-color: #ffffff;
            color: #000000;
            text-align: center;
            padding: 20px;
            margin-bottom: 30px;
            border-radius: 5px;
            border: 1px solid #000000;
        }
        
        .header h1 {
            color: #000000;
            margin: 0;
            padding: 0;
            font-size: 24px;
        }
        
        .header p {
            color: #000000;
            margin: 5px 0;
        }
        
        .location-badge {
            background-color: #ffffff;
            color: #000000;
            padding: 5px 15px;
            border-radius: 15px;
            display: inline-block;
            margin-top: 10px;
            border: 1px solid #000000;
            font-weight: bold;
        }

        .summary {
            background-color: #ffffff;
            padding: 20px;
            margin: 20px 0;
            border-radius: 5px;
            border: 1px solid #000000;
        }

        .stat-box {
            display: inline-block;
            width: 22%;
            margin: 1%;
            padding: 15px;
            background-color: #ffffff;
            border: 1px solid #000000;
            border-radius: 5px;
            text-align: center;
        }

        .stat-box strong {
            display: block;
            margin-bottom: 5px;
            color: #000000;
        }

        .section-title {
            background-color: #ffffff;
            color: #000000;
            padding: 10px 15px;
            margin: 30px 0 15px 0;
            border-radius: 5px;
            font-size: 14px;
            font-weight: bold;
            border: 1px solid #000000;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
            background-color: #ffffff;
        }

        th {
            background-color: #ffffff;
            color: #000000;
            padding: 12px 8px;
            text-align: left;
            font-weight: bold;
            font-size: 11px;
            border: 1px solid #000000;
        }

        td {
            padding: 10px 8px;
            border: 1px solid #000000;
            font-size: 11px;
            color: #000000;
        }

        tr:nth-child(even) {
            background-color: #ffffff;
        }

        .vaccination-status {
            padding: 4px 8px;
            border-radius: 12px;
            font-size: 10px;
            font-weight: bold;
            display: inline-block;
            border: 1px solid #000000;
        }

        .status-yes {
            background-color: #ffffff;
            color: #000000;
            border-color: #000000;
        }

        .status-no {
            background-color: #ffffff;
            color: #000000;
            border-color: #000000;
        }

        .status-not-required {
            background-color: #ffffff;
            color: #000000;
            border-color: #000000;
        }

        .footer {
            position: fixed;
            bottom: 30px;
            left: 0;
            right: 0;
            text-align: center;
            color: #000000;
            font-size: 10px;
            border-top: 1px solid #000000;
            padding-top: 10px;
            background-color: #ffffff;
        }

        .page-break {
            page-break-after: always;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Animal Report</h1>
        <p>Generated by: {{ auth()->user()->complete_name }}</p>
        <p>{{ $dateFrom->format('F d, Y') }} - {{ $dateTo->format('F d, Y') }}</p>
        <div class="location-badge">
            {{ isset($barangay_name) ? $barangay_name : 'All Barangays' }}
        </div>
    </div>

    <div class="summary">
        <div class="section-title">Summary Statistics</div>
        <div style="margin-top: 15px;">
            <div class="stat-box">
                <strong>Total Animals</strong>
                <span style="font-size: 18px;">{{ $summary['total'] }}</span>
            </div>
            <div class="stat-box">
                <strong>Vaccinated</strong>
                <span style="font-size: 18px;">{{ $summary['vaccinated'] }}</span>
            </div>
            <div class="stat-box">
                <strong>Not Vaccinated</strong>
                <span style="font-size: 18px;">{{ $summary['nonVaccinated'] }}</span>
            </div>
            <div class="stat-box">
                <strong>No Vaccination Required</strong>
                <span style="font-size: 18px;">{{ $summary['notRequired'] }}</span>
            </div>
        </div>
    </div>

    <div class="section-title">Animals by Species</div>
    <table>
        <thead>
            <tr>
                <th>Species</th>
                <th>Total</th>
                <th>Vaccinated</th>
                <th>Not Vaccinated</th>
                <th>No Vaccination Required</th>
            </tr>
        </thead>
        <tbody>
            @foreach($summary['bySpecies'] as $species => $data)
                <tr>
                    <td><strong>{{ $species }}</strong></td>
                    <td>{{ $data['count'] }}</td>
                    <td>{{ $data['vaccinated'] }}</td>
                    <td>{{ $data['nonVaccinated'] }}</td>
                    <td>{{ $data['notRequired'] }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="section-title">Animals by Breed</div>
    <table>
        <thead>
            <tr>
                <th>Breed</th>
                <th>Total</th>
                <th>Vaccinated</th>
                <th>Not Vaccinated</th>
                <th>No Vaccination Required</th>
            </tr>
        </thead>
        <tbody>
            @foreach($summary['byBreed'] as $breed => $data)
                <tr>
                    <td><strong>{{ $breed }}</strong></td>
                    <td>{{ $data['count'] }}</td>
                    <td>{{ $data['vaccinated'] }}</td>
                    <td>{{ $data['nonVaccinated'] }}</td>
                    <td>{{ $data['notRequired'] }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="section-title">Animal List</div>
    <table>
        <thead>
            <tr>
                <th>Animal Name</th>
                <th>Species</th>
                <th>Breed</th>
                <th>Owner</th>
                <th>Barangay</th>
                <th>Vaccination Status</th>
                <th>Date Registered</th>
            </tr>
        </thead>
        <tbody>
            @foreach($animals as $animal)
                <tr>
                    <td><strong>{{ $animal->name }}</strong></td>
                    <td>{{ $animal->species->name ?? 'N/A' }}</td>
                    <td>{{ $animal->breed->name ?? 'N/A' }}</td>
                    <td>{{ $animal->owner->user->complete_name ?? 'N/A' }}</td>
                    <td>{{ $animal->owner->user->address->barangay->barangay_name ?? 'N/A' }}</td>
                    <td>
                        @if($animal->is_vaccinated === 1)
                            <span class="vaccination-status status-yes">Vaccinated</span>
                        @elseif($animal->is_vaccinated === 0)
                            <span class="vaccination-status status-no">Not Vaccinated</span>
                        @else
                            <span class="vaccination-status status-not-required">Not Required</span>
                        @endif
                    </td>
                    <td>{{ \Carbon\Carbon::parse($animal->created_at)->format('M d, Y') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Animal Report | Generated on {{ now()->format('F d, Y h:i A') }}
        <br>
        Page {PAGE_NUM} of {PAGE_COUNT}
    </div>
</body>
</html>
